from __future__ import annotations

# Canonical lower-case terms used for deterministic keyword extraction and
# "exact match" scoring. Keep this list reasonably small and focused on common
# resume/JD technical keywords.
TECH_TERMS: list[str] = [
    # Languages / core
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "go",
    "golang",
    "rust",
    "scala",
    "r",
    "bash",
    "regex",
    # Data / ML
    "sql",
    "nosql",
    "mongodb",
    "mysql",
    "postgresql",
    "redis",
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "pytorch",
    "tensorflow",
    "keras",
    "spacy",
    "xgboost",
    "lightgbm",
    # GenAI / LLM
    "llm",
    "rag",
    "langchain",
    "langgraph",
    "vector database",
    "embedding",
    "transformer",
    "bert",
    "gpt",
    # Platforms / infra
    "docker",
    "kubernetes",
    "aws",
    "gcp",
    "azure",
    "aws lambda",
    "s3",
    "dynamodb",
    "mlflow",
    "airflow",
    "dbt",
    # Web / APIs
    "fastapi",
    "flask",
    "django",
    "react",
    "node.js",
    "elasticsearch",
    # Domains
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "cv",
    "mlops",
    "ci/cd",
]
